// <auto-generated />
using System;
using System.Collections.Generic;
using CathedrAll.Pessoas.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CathedrAll.Pessoas.Migrations
{
    [DbContext(typeof(PessoasDbContext))]
    partial class PessoasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pessoas")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CathedrAll.Pessoas.Domain.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular");

                    b.Property<Guid?>("ConvidadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("convidado_por_id");

                    b.Property<DateOnly?>("DataBatismo")
                        .HasColumnType("date")
                        .HasColumnName("data_batismo");

                    b.Property<DateOnly?>("DataCasamento")
                        .HasColumnType("date")
                        .HasColumnName("data_casamento");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_civil");

                    b.Property<Guid?>("FundidaEmId")
                        .HasColumnType("uuid")
                        .HasColumnName("fundida_em_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Profissao")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("profissao");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Endereco", "CathedrAll.Pessoas.Domain.Pessoa.Endereco#Endereco", b1 =>
                        {
                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("endereco_bairro");

                            b1.Property<string>("Cep")
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("endereco_cep");

                            b1.Property<string>("Cidade")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("endereco_cidade");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("endereco_complemento");

                            b1.Property<string>("Logradouro")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("endereco_logradouro");

                            b1.Property<string>("Numero")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("endereco_numero");

                            b1.Property<string>("Uf")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("endereco_uf");
                        });

                    b.HasKey("Id")
                        .HasName("pk_pessoas");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_pessoas_nome");

                    b.ToTable("pessoas", "pessoas");
                });

            modelBuilder.Entity("CathedrAll.Pessoas.Domain.VinculoIgreja", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("situacao");

                    b.HasKey("Id")
                        .HasName("pk_vinculos_igreja");

                    b.HasIndex("PessoaId", "DataFim")
                        .HasDatabaseName("ix_vinculos_igreja_pessoa_id_data_fim");

                    b.ToTable("vinculos_igreja", "pessoas");
                });

            modelBuilder.Entity("CathedrAll.Pessoas.Domain.VinculoIgreja", b =>
                {
                    b.HasOne("CathedrAll.Pessoas.Domain.Pessoa", null)
                        .WithMany("Vinculos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vinculos_igreja_pessoas_pessoa_id");
                });

            modelBuilder.Entity("CathedrAll.Pessoas.Domain.Pessoa", b =>
                {
                    b.Navigation("Vinculos");
                });
#pragma warning restore 612, 618
        }
    }
}
