<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../Kernel/CathedrAll.Kernel.Domain/CathedrAll.Kernel.Domain.csproj" />
    <ProjectReference Include="../../Kernel/CathedrAll.Kernel.Infrastructure/CathedrAll.Kernel.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CathedrAll.Pessoas.Tests" />
  </ItemGroup>

</Project>
